//! Large English corpus and knowledge base for TLE-Chat.
//!
//! All data is `&'static str` for zero-allocation at runtime.
//! No external dependencies beyond std.

/// Returns 500+ diverse English sentences covering multiple topics.
pub fn large_corpus() -> Vec<&'static str> {
    vec![
        // ═══════════════════════════════════════════════════════
        // Everyday facts (50+)
        // ═══════════════════════════════════════════════════════
        "The sun rises in the east.",
        "Water is essential for life.",
        "Most people sleep at night.",
        "The sky appears blue during the day.",
        "Gravity pulls objects toward the ground.",
        "A year has twelve months.",
        "There are seven days in a week.",
        "Humans need oxygen to breathe.",
        "The moon orbits the Earth.",
        "Fire is hot and can burn things.",
        "Ice melts when it gets warm.",
        "Sound travels through the air.",
        "Light travels faster than sound.",
        "A circle has no corners.",
        "The alphabet has twenty-six letters.",
        "Most cars run on gasoline or electricity.",
        "Clocks measure the passage of time.",
        "Books contain written words and ideas.",
        "Mirrors reflect light and images.",
        "Scissors are used to cut paper.",
        "Keys are used to open locks.",
        "Shoes protect your feet from the ground.",
        "Soap helps remove dirt from skin.",
        "Umbrellas keep you dry in the rain.",
        "Glasses help people see more clearly.",
        "Bridges connect land across water.",
        "Roads are built for vehicles to travel on.",
        "Windows let light into buildings.",
        "Doors provide entry and exit to rooms.",
        "Stairs connect different floors of a building.",
        "Paint is used to color surfaces.",
        "Glue holds objects together.",
        "Wheels allow objects to roll easily.",
        "Maps show the layout of an area.",
        "Calendars display dates and days.",
        "Thermometers measure temperature.",
        "Batteries store electrical energy.",
        "Magnets attract iron and steel.",
        "Rubber is a flexible material.",
        "Glass is transparent and fragile.",
        "Cotton is a soft natural fabric.",
        "Paper is made from wood pulp.",
        "Metal is strong and conducts electricity.",
        "Plastic is lightweight and durable.",
        "Concrete is used to build structures.",
        "Bricks are used to construct walls.",
        "Nails hold pieces of wood together.",
        "Rope is used for tying and pulling.",
        "Candles produce light when burned.",
        "Matches can start a fire.",
        "Coins are small pieces of metal currency.",
        "Stamps are placed on letters for mailing.",
        // ═══════════════════════════════════════════════════════
        // Animal facts (50+)
        // ═══════════════════════════════════════════════════════
        "Cats are small animals that eat fish.",
        "Dogs are loyal companions to humans.",
        "Elephants are the largest land animals.",
        "Dolphins are intelligent marine mammals.",
        "Eagles have excellent vision for hunting.",
        "Penguins cannot fly but swim very well.",
        "Horses have been used for transportation for centuries.",
        "Cows produce milk that humans drink.",
        "Chickens lay eggs almost every day.",
        "Bees make honey from flower nectar.",
        "Spiders spin webs to catch insects.",
        "Snakes have no legs and slither on the ground.",
        "Frogs can live both in water and on land.",
        "Fish breathe through gills underwater.",
        "Birds build nests to lay their eggs.",
        "Ants live in large colonies underground.",
        "Butterflies begin life as caterpillars.",
        "Whales are the largest animals on Earth.",
        "Sharks have been around for millions of years.",
        "Turtles carry their homes on their backs.",
        "Rabbits have long ears and hop quickly.",
        "Bears hibernate during the winter months.",
        "Owls are nocturnal birds of prey.",
        "Parrots can mimic human speech.",
        "Giraffes have the longest necks of any animal.",
        "Lions are known as the king of the jungle.",
        "Tigers are the largest wild cats.",
        "Wolves hunt in packs for larger prey.",
        "Foxes are clever and adaptable animals.",
        "Deer shed and regrow their antlers each year.",
        "Squirrels store nuts for the winter.",
        "Bats are the only mammals that can fly.",
        "Crocodiles have powerful jaws and sharp teeth.",
        "Kangaroos carry their young in a pouch.",
        "Koalas eat eucalyptus leaves almost exclusively.",
        "Pandas eat bamboo as their primary food.",
        "Monkeys are intelligent primates that live in groups.",
        "Gorillas are the largest primates on Earth.",
        "Cheetahs are the fastest land animals.",
        "Camels can survive days without water.",
        "Polar bears live in the Arctic region.",
        "Octopuses have eight arms and are very smart.",
        "Seahorses are tiny fish shaped like horses.",
        "Flamingos are pink because of their diet.",
        "Peacocks display colorful tail feathers.",
        "Hummingbirds can hover in mid-air.",
        "Woodpeckers peck trees to find insects.",
        "Salmon swim upstream to spawn.",
        "Jellyfish have no brain or bones.",
        "Starfish can regrow their arms.",
        "Chameleons change color to communicate.",
        "Sloths move very slowly through trees.",
        // ═══════════════════════════════════════════════════════
        // Geography (50+)
        // ═══════════════════════════════════════════════════════
        "Tokyo is the capital of Japan.",
        "Paris is the capital of France.",
        "London is the capital of England.",
        "Berlin is the capital of Germany.",
        "Rome is the capital of Italy.",
        "Madrid is the capital of Spain.",
        "Moscow is the capital of Russia.",
        "Beijing is the capital of China.",
        "Washington is the capital of the United States.",
        "Canberra is the capital of Australia.",
        "Ottawa is the capital of Canada.",
        "Cairo is the capital of Egypt.",
        "New Delhi is the capital of India.",
        "Bangkok is the capital of Thailand.",
        "Seoul is the capital of South Korea.",
        "The Nile is the longest river in Africa.",
        "The Amazon is the largest river by volume.",
        "Mount Everest is the tallest mountain on Earth.",
        "The Sahara is the largest hot desert.",
        "The Pacific Ocean is the largest ocean.",
        "Antarctica is the coldest continent.",
        "Africa is the second largest continent.",
        "Europe has many different countries and languages.",
        "Asia is the largest continent by area.",
        "South America contains the Amazon rainforest.",
        "Australia is both a country and a continent.",
        "The Great Wall of China is visible from space.",
        "The Grand Canyon is located in Arizona.",
        "Niagara Falls borders the US and Canada.",
        "The Mediterranean Sea is between Europe and Africa.",
        "Iceland is known for its volcanoes and glaciers.",
        "Brazil is the largest country in South America.",
        "Russia is the largest country by area.",
        "China has the largest population in the world.",
        "India is the second most populous country.",
        "Japan is an island nation in East Asia.",
        "Mexico is located south of the United States.",
        "The United Kingdom includes England and Scotland.",
        "Greece is known for ancient civilization.",
        "Egypt has pyramids built thousands of years ago.",
        "Switzerland is known for mountains and chocolate.",
        "The Dead Sea is the lowest point on land.",
        "Hawaii is a group of islands in the Pacific.",
        "The Alps are a mountain range in Europe.",
        "The Andes are the longest mountain range.",
        "Madagascar is a large island off Africa.",
        "New Zealand has two main islands.",
        "The Arctic is at the top of the Earth.",
        "The Equator divides Earth into two halves.",
        "The Atlantic Ocean separates Europe from America.",
        "Venice is a city built on water.",
        "Dubai is known for tall modern buildings.",
        // ═══════════════════════════════════════════════════════
        // Science (50+)
        // ═══════════════════════════════════════════════════════
        "Water boils at 100 degrees celsius.",
        "The Earth revolves around the Sun.",
        "Atoms are the building blocks of matter.",
        "DNA carries genetic information.",
        "Photosynthesis converts sunlight to energy.",
        "The speed of light is about 300000 kilometers per second.",
        "Oxygen makes up about 21 percent of the atmosphere.",
        "Nitrogen makes up about 78 percent of the atmosphere.",
        "The human body has 206 bones.",
        "The heart pumps blood through the body.",
        "The brain controls all body functions.",
        "Cells are the basic units of life.",
        "Gravity keeps planets in orbit around the Sun.",
        "Sound cannot travel through a vacuum.",
        "Electricity flows through conductive materials.",
        "Magnets have north and south poles.",
        "Chemical reactions rearrange atoms into new substances.",
        "Temperature measures the kinetic energy of molecules.",
        "Pressure increases with depth underwater.",
        "Light can behave as both a wave and a particle.",
        "The periodic table organizes chemical elements.",
        "Iron is attracted to magnets.",
        "Carbon dioxide is exhaled by humans.",
        "Plants absorb carbon dioxide from the air.",
        "Evolution explains how species change over time.",
        "Volcanoes release magma from deep underground.",
        "Earthquakes occur along fault lines.",
        "The ozone layer protects from ultraviolet radiation.",
        "Stars produce energy through nuclear fusion.",
        "Planets reflect light from their star.",
        "Mars is called the Red Planet.",
        "Jupiter is the largest planet in our solar system.",
        "Saturn has visible rings made of ice and rock.",
        "Mercury is the closest planet to the Sun.",
        "Venus is the hottest planet in our solar system.",
        "Neptune is the farthest planet from the Sun.",
        "Pluto is classified as a dwarf planet.",
        "The Moon causes tides on Earth.",
        "Fossil fuels are formed from ancient organisms.",
        "Renewable energy comes from sources like wind and solar.",
        "Vaccines help the immune system fight diseases.",
        "Antibiotics kill or inhibit bacteria.",
        "Viruses are smaller than bacteria.",
        "The human genome has about three billion base pairs.",
        "Mitochondria produce energy for cells.",
        "Photons are particles of light.",
        "Electrons orbit the nucleus of an atom.",
        "Protons have a positive electrical charge.",
        "Neutrons have no electrical charge.",
        "Acids have a pH below seven.",
        "Bases have a pH above seven.",
        "Pure water has a neutral pH of seven.",
        // ═══════════════════════════════════════════════════════
        // Common activities (50+)
        // ═══════════════════════════════════════════════════════
        "She walked to the store and bought milk.",
        "He rides his bicycle to work every morning.",
        "They played soccer in the park after school.",
        "The children built a sandcastle on the beach.",
        "She reads a book before going to sleep.",
        "He cooks dinner for his family every evening.",
        "They went hiking in the mountains last weekend.",
        "The students studied hard for their exams.",
        "She listens to music while exercising.",
        "He takes the bus to get to school.",
        "They planted flowers in the garden together.",
        "The teacher explained the lesson clearly.",
        "She brushes her teeth twice a day.",
        "He feeds the dog every morning.",
        "They watched a movie at the cinema.",
        "The family ate dinner together at the table.",
        "She washes her hands before eating.",
        "He opened the window to let in fresh air.",
        "They cleaned the house on Saturday morning.",
        "The boy threw the ball to his friend.",
        "She drew a picture of a sunset.",
        "He wrote a letter to his grandmother.",
        "They danced at the party until midnight.",
        "The woman carried groceries home from the market.",
        "She tied her shoelaces before running.",
        "He poured water into the glass.",
        "They set up the tent at the campsite.",
        "The girl climbed the tree in the backyard.",
        "She folded the laundry and put it away.",
        "He mowed the lawn every Saturday.",
        "They swam in the lake during summer.",
        "The man fixed the broken chair with glue.",
        "She packed her suitcase for the trip.",
        "He locked the door before leaving home.",
        "They drove to the airport early in the morning.",
        "The baker made fresh bread every day.",
        "She watered the plants in the morning.",
        "He checked his email after breakfast.",
        "They organized the bookshelf by color.",
        "The nurse took the patient's temperature.",
        "She answered the phone on the second ring.",
        "He parked the car in the garage.",
        "They decorated the room for the birthday party.",
        "The mechanic repaired the engine quickly.",
        "She counted the money in her wallet.",
        "He sharpened the pencil before writing.",
        "They walked the dog around the neighborhood.",
        "The pilot flew the plane through the clouds.",
        "She ironed her shirt for the interview.",
        "He shoveled snow from the driveway.",
        "They painted the fence white.",
        "The librarian arranged books on the shelves.",
        // ═══════════════════════════════════════════════════════
        // Emotions and social (50+)
        // ═══════════════════════════════════════════════════════
        "He was happy to see his friends.",
        "She felt proud after finishing the marathon.",
        "The child cried when he lost his toy.",
        "They laughed together at the funny joke.",
        "He was nervous before the big presentation.",
        "She felt relieved when the test was over.",
        "The couple celebrated their anniversary with joy.",
        "He was surprised by the birthday party.",
        "She felt grateful for her family's support.",
        "They were excited about the upcoming vacation.",
        "He felt lonely living far from home.",
        "She was angry when someone broke her vase.",
        "The team was disappointed after losing the game.",
        "He felt confident in his abilities.",
        "She was curious about the mysterious package.",
        "They felt compassion for the injured animal.",
        "He was embarrassed by his mistake.",
        "She felt calm after meditating for ten minutes.",
        "The audience was moved by the beautiful music.",
        "He was frustrated with the difficult puzzle.",
        "She felt hopeful about the future.",
        "They were anxious about the exam results.",
        "He was content sitting by the fire.",
        "She felt inspired by the motivational speech.",
        "The friends were supportive during tough times.",
        "He was jealous of his brother's new toy.",
        "She felt nostalgic looking at old photographs.",
        "They were enthusiastic about starting the project.",
        "He was terrified of the thunderstorm.",
        "She felt peaceful walking through the garden.",
        "The mother was worried about her sick child.",
        "He was amused by the cat's playful behavior.",
        "She felt determined to achieve her goals.",
        "They were shocked by the unexpected news.",
        "He was bored during the long meeting.",
        "She felt sympathy for her friend's loss.",
        "The crowd was thrilled by the concert.",
        "He was ashamed of what he had done.",
        "She felt optimistic about the new opportunity.",
        "They were confused by the complicated instructions.",
        "He was delighted with the birthday present.",
        "She felt brave facing her fears.",
        "The children were gleeful playing in the snow.",
        "He was melancholic on rainy days.",
        "She felt secure in her partner's arms.",
        "They were resentful about the unfair decision.",
        "He was overwhelmed by all the responsibilities.",
        "She felt free running along the beach.",
        "The baby was content after being fed.",
        "He was skeptical of the too-good offer.",
        "She felt triumphant after winning the debate.",
        "They celebrated together after the good news.",
        // ═══════════════════════════════════════════════════════
        // Time and weather (50+)
        // ═══════════════════════════════════════════════════════
        "It rains a lot in the spring.",
        "Snow falls during the cold winter months.",
        "Summer days are long and warm.",
        "Autumn leaves change color and fall from trees.",
        "The sun sets earlier in winter.",
        "Thunder often follows lightning in a storm.",
        "Fog makes it difficult to see the road.",
        "Hurricanes form over warm ocean water.",
        "Tornadoes can destroy buildings in seconds.",
        "The wind blows stronger near the coast.",
        "Clouds form when water vapor condenses.",
        "Rainbows appear after rain when the sun shines.",
        "Hail consists of balls of ice falling from clouds.",
        "Droughts occur when there is no rain for a long time.",
        "Floods happen when rivers overflow their banks.",
        "The temperature drops at night.",
        "Morning dew forms on grass overnight.",
        "Frost covers windows on cold mornings.",
        "Monsoons bring heavy rain to tropical areas.",
        "Blizzards combine heavy snow with strong winds.",
        "The longest day of the year is the summer solstice.",
        "The shortest day is the winter solstice.",
        "Spring is when flowers begin to bloom.",
        "Autumn is also called fall in America.",
        "Daylight saving time changes clocks by one hour.",
        "Midnight marks the start of a new day.",
        "Noon is when the sun is highest in the sky.",
        "Dawn is the time just before sunrise.",
        "Dusk is the time just after sunset.",
        "A decade is a period of ten years.",
        "A century lasts one hundred years.",
        "Leap years have an extra day in February.",
        "The weather forecast predicts future conditions.",
        "Barometers measure atmospheric pressure.",
        "High pressure usually means clear skies.",
        "Low pressure often brings rain and clouds.",
        "Climate describes long-term weather patterns.",
        "Global warming is increasing average temperatures.",
        "Glaciers are melting due to rising temperatures.",
        "Seasons change because Earth's axis is tilted.",
        "The equinox occurs twice a year with equal day and night.",
        "Tropical regions are warm all year round.",
        "Polar regions are extremely cold most of the time.",
        "Temperate zones have four distinct seasons.",
        "Humidity measures the amount of moisture in air.",
        "A thermometer reads temperature in degrees.",
        "Wind speed is measured with an anemometer.",
        "Snowflakes have unique crystalline shapes.",
        "Sleet is a mixture of rain and ice.",
        "Heat waves can be dangerous for health.",
        "Cold fronts bring sudden drops in temperature.",
        // ═══════════════════════════════════════════════════════
        // Food and cooking (50+)
        // ═══════════════════════════════════════════════════════
        "Rice is a common food in Asia.",
        "Bread is made from flour, water, and yeast.",
        "Pasta comes from Italy originally.",
        "Sushi is a traditional Japanese dish.",
        "Pizza originated in Naples, Italy.",
        "Chocolate is made from cacao beans.",
        "Coffee beans are roasted before brewing.",
        "Tea is one of the most popular drinks worldwide.",
        "Cheese is made from milk through fermentation.",
        "Butter is churned from cream.",
        "Eggs are used in many recipes for baking.",
        "Sugar sweetens food and beverages.",
        "Salt enhances the flavor of food.",
        "Pepper is a common spice used worldwide.",
        "Olive oil is used for cooking in Mediterranean cuisine.",
        "Garlic adds flavor to many savory dishes.",
        "Onions are a base ingredient in many recipes.",
        "Tomatoes are used in sauces and salads.",
        "Potatoes can be baked, fried, or boiled.",
        "Carrots are orange root vegetables rich in vitamins.",
        "Spinach is a nutritious green leafy vegetable.",
        "Bananas are a popular yellow fruit.",
        "Apples come in many varieties and colors.",
        "Oranges are citrus fruits rich in vitamin C.",
        "Strawberries are red berries often eaten fresh.",
        "Grapes are used to make wine.",
        "Lemons are sour citrus fruits.",
        "Watermelon is refreshing on hot summer days.",
        "Coconut provides milk, oil, and meat.",
        "Almonds are nutritious tree nuts.",
        "Chicken is one of the most consumed meats.",
        "Beef comes from cattle.",
        "Pork is meat from pigs.",
        "Salmon is a popular fish for cooking.",
        "Shrimp are small shellfish used in many cuisines.",
        "Tofu is made from soybeans.",
        "Yogurt is a fermented dairy product.",
        "Honey is a natural sweetener made by bees.",
        "Cinnamon is a warm spice from tree bark.",
        "Vanilla is used to flavor desserts.",
        "Baking requires precise measurements of ingredients.",
        "Grilling cooks food over direct heat.",
        "Boiling involves heating liquid to 100 degrees.",
        "Frying cooks food in hot oil.",
        "Steaming preserves nutrients better than boiling.",
        "Roasting uses dry heat in an oven.",
        "A sharp knife makes chopping vegetables easier.",
        "Soup is made by simmering ingredients in broth.",
        "Salad is usually served cold with dressing.",
        "Curry is a spiced dish popular in India.",
        "Tacos are a traditional Mexican food.",
        "Dumplings are found in many world cuisines.",
        // ═══════════════════════════════════════════════════════
        // Technology (50+)
        // ═══════════════════════════════════════════════════════
        "Computers can process information quickly.",
        "The internet connects millions of devices worldwide.",
        "Smartphones combine a phone with a computer.",
        "Email allows instant written communication.",
        "Software is a set of instructions for computers.",
        "Hardware refers to the physical parts of a computer.",
        "Processors execute billions of calculations per second.",
        "Memory stores data that the computer is using.",
        "Hard drives store data permanently.",
        "Keyboards are used to type text into computers.",
        "Monitors display visual output from computers.",
        "Printers produce physical copies of digital documents.",
        "WiFi provides wireless internet connections.",
        "Bluetooth connects devices over short distances.",
        "GPS helps determine your location on Earth.",
        "Satellites orbit Earth and relay communications.",
        "Robots can perform repetitive tasks automatically.",
        "Artificial intelligence mimics human thinking.",
        "Machine learning improves with more data.",
        "Algorithms are step-by-step problem-solving procedures.",
        "Programming languages are used to write software.",
        "Databases store and organize large amounts of data.",
        "Cloud computing provides remote server access.",
        "Encryption protects data from unauthorized access.",
        "Passwords secure accounts from intruders.",
        "Firewalls protect networks from attacks.",
        "Updates fix bugs and improve software security.",
        "Browsers are used to access websites.",
        "Search engines help find information online.",
        "Social media connects people around the world.",
        "Video calls allow face-to-face remote communication.",
        "Streaming delivers media content in real time.",
        "Digital cameras capture photos as electronic files.",
        "Touchscreens respond to finger contact.",
        "Virtual reality creates immersive digital environments.",
        "Augmented reality overlays digital content on the real world.",
        "Three-dimensional printers create physical objects from designs.",
        "Electric vehicles use batteries instead of gasoline.",
        "Solar panels convert sunlight into electricity.",
        "Wind turbines generate power from moving air.",
        "Fiber optic cables transmit data using light.",
        "Microchips power most modern electronic devices.",
        "Operating systems manage computer hardware and software.",
        "Apps are programs designed for specific tasks.",
        "USB ports connect peripheral devices to computers.",
        "Servers store and deliver web content.",
        "Routers direct internet traffic between networks.",
        "Binary code uses only zeros and ones.",
        "Pixels are tiny dots that make up digital images.",
        "Scanners convert physical documents to digital files.",
        "Headphones deliver audio directly to your ears.",
        // ═══════════════════════════════════════════════════════
        // Nature (50+)
        // ═══════════════════════════════════════════════════════
        "Trees produce oxygen from sunlight.",
        "Forests cover about thirty percent of Earth's land.",
        "Oceans contain most of Earth's water.",
        "Rivers carry water from mountains to the sea.",
        "Lakes are bodies of fresh water surrounded by land.",
        "Deserts receive very little rainfall.",
        "Rainforests have the highest biodiversity on Earth.",
        "Coral reefs support thousands of marine species.",
        "Wetlands filter water and prevent flooding.",
        "Grasslands are home to many grazing animals.",
        "Mountains are formed by tectonic plate movements.",
        "Caves are natural underground chambers.",
        "Waterfalls form where rivers flow over cliffs.",
        "Islands are land surrounded by water.",
        "Volcanoes can create new land when they erupt.",
        "Glaciers are massive rivers of ice.",
        "Soil is made of minerals, water, and organic matter.",
        "Seeds grow into new plants with water and sunlight.",
        "Flowers attract pollinators with color and scent.",
        "Roots anchor plants and absorb water from soil.",
        "Leaves capture sunlight for photosynthesis.",
        "Bark protects tree trunks from damage.",
        "Moss grows in damp and shaded areas.",
        "Ferns are ancient plants that reproduce with spores.",
        "Mushrooms are fungi that grow in moist conditions.",
        "Algae produce much of Earth's oxygen.",
        "Ecosystems are communities of living organisms.",
        "Food chains show how energy passes between organisms.",
        "Predators hunt other animals for food.",
        "Herbivores eat only plants.",
        "Omnivores eat both plants and animals.",
        "Migration is the seasonal movement of animals.",
        "Hibernation helps animals survive cold winters.",
        "Camouflage helps animals hide from predators.",
        "Symbiosis is a close relationship between species.",
        "Pollination is essential for many plants to reproduce.",
        "Decomposers break down dead organic matter.",
        "The water cycle moves water between Earth and atmosphere.",
        "Erosion wears away rock and soil over time.",
        "Fossils are preserved remains of ancient life.",
        "Minerals form naturally in the Earth's crust.",
        "Crystals have a regular repeating atomic structure.",
        "Geysers shoot hot water and steam from underground.",
        "Tides are caused by the Moon's gravitational pull.",
        "Currents move water through the oceans.",
        "Seasons affect plant growth and animal behavior.",
        "Biodiversity is the variety of life in an area.",
        "Endangered species are at risk of extinction.",
        "Conservation protects natural habitats and wildlife.",
        "National parks preserve natural landscapes.",
        "Climate zones determine what plants can grow.",
        "Photosynthesis requires sunlight, water, and carbon dioxide.",
    ]
}

/// Returns 300+ fact triples as (subject, relation, object).
pub fn knowledge_base() -> Vec<(&'static str, &'static str, &'static str)> {
    vec![
        // ═══════════════════════════════════════════════════════
        // Animals
        // ═══════════════════════════════════════════════════════
        ("cat", "is_a", "animal"),
        ("cat", "has", "fur"),
        ("cat", "has", "whiskers"),
        ("cat", "has", "tail"),
        ("cat", "eats", "fish"),
        ("cat", "eats", "mice"),
        ("cat", "can", "climb_trees"),
        ("cat", "can", "purr"),
        ("cat", "is", "small"),
        ("dog", "is_a", "animal"),
        ("dog", "has", "fur"),
        ("dog", "has", "tail"),
        ("dog", "eats", "meat"),
        ("dog", "eats", "bones"),
        ("dog", "can", "bark"),
        ("dog", "can", "fetch"),
        ("dog", "can", "swim"),
        ("dog", "is", "loyal"),
        ("elephant", "is_a", "animal"),
        ("elephant", "has", "trunk"),
        ("elephant", "has", "tusks"),
        ("elephant", "has", "large_ears"),
        ("elephant", "eats", "plants"),
        ("elephant", "is", "large"),
        ("elephant", "is", "gray"),
        ("elephant", "can", "swim"),
        ("horse", "is_a", "animal"),
        ("horse", "has", "mane"),
        ("horse", "has", "hooves"),
        ("horse", "eats", "grass"),
        ("horse", "eats", "hay"),
        ("horse", "can", "run_fast"),
        ("horse", "can", "jump"),
        ("horse", "is", "strong"),
        ("bird", "is_a", "animal"),
        ("bird", "has", "wings"),
        ("bird", "has", "feathers"),
        ("bird", "has", "beak"),
        ("bird", "can", "fly"),
        ("bird", "can", "sing"),
        ("bird", "eats", "seeds"),
        ("bird", "eats", "insects"),
        ("fish", "is_a", "animal"),
        ("fish", "has", "fins"),
        ("fish", "has", "scales"),
        ("fish", "has", "gills"),
        ("fish", "can", "swim"),
        ("fish", "lives_in", "water"),
        ("fish", "is", "cold_blooded"),
        ("lion", "is_a", "animal"),
        ("lion", "has", "mane"),
        ("lion", "has", "claws"),
        ("lion", "eats", "meat"),
        ("lion", "can", "roar"),
        ("lion", "is", "strong"),
        ("lion", "lives_in", "africa"),
        ("tiger", "is_a", "animal"),
        ("tiger", "has", "stripes"),
        ("tiger", "has", "claws"),
        ("tiger", "eats", "meat"),
        ("tiger", "can", "swim"),
        ("tiger", "is", "large"),
        ("tiger", "lives_in", "asia"),
        ("bear", "is_a", "animal"),
        ("bear", "has", "fur"),
        ("bear", "has", "claws"),
        ("bear", "eats", "fish"),
        ("bear", "eats", "berries"),
        ("bear", "can", "climb_trees"),
        ("bear", "can", "hibernate"),
        ("bear", "is", "strong"),
        ("whale", "is_a", "animal"),
        ("whale", "is_a", "mammal"),
        ("whale", "has", "blowhole"),
        ("whale", "lives_in", "ocean"),
        ("whale", "eats", "krill"),
        ("whale", "is", "enormous"),
        ("whale", "can", "sing"),
        ("dolphin", "is_a", "animal"),
        ("dolphin", "is_a", "mammal"),
        ("dolphin", "lives_in", "ocean"),
        ("dolphin", "can", "jump"),
        ("dolphin", "is", "intelligent"),
        ("dolphin", "eats", "fish"),
        ("eagle", "is_a", "bird"),
        ("eagle", "has", "sharp_talons"),
        ("eagle", "can", "fly_high"),
        ("eagle", "eats", "fish"),
        ("eagle", "is", "powerful"),
        ("penguin", "is_a", "bird"),
        ("penguin", "lives_in", "antarctica"),
        ("penguin", "can", "swim"),
        ("penguin", "cannot", "fly"),
        ("penguin", "eats", "fish"),
        ("shark", "is_a", "fish"),
        ("shark", "has", "sharp_teeth"),
        ("shark", "lives_in", "ocean"),
        ("shark", "eats", "fish"),
        ("shark", "is", "dangerous"),
        ("snake", "is_a", "reptile"),
        ("snake", "has", "scales"),
        ("snake", "has_no", "legs"),
        ("snake", "can", "slither"),
        ("snake", "eats", "rodents"),
        ("frog", "is_a", "amphibian"),
        ("frog", "can", "jump"),
        ("frog", "can", "swim"),
        ("frog", "eats", "insects"),
        ("frog", "lives_in", "ponds"),
        ("butterfly", "is_a", "insect"),
        ("butterfly", "has", "wings"),
        ("butterfly", "can", "fly"),
        ("butterfly", "eats", "nectar"),
        ("bee", "is_a", "insect"),
        ("bee", "makes", "honey"),
        ("bee", "has", "stinger"),
        ("bee", "can", "fly"),
        ("bee", "eats", "nectar"),
        ("spider", "is_a", "arachnid"),
        ("spider", "has", "eight_legs"),
        ("spider", "can", "spin_webs"),
        ("spider", "eats", "insects"),
        ("rabbit", "is_a", "animal"),
        ("rabbit", "has", "long_ears"),
        ("rabbit", "eats", "carrots"),
        ("rabbit", "eats", "grass"),
        ("rabbit", "can", "hop"),
        ("rabbit", "is", "soft"),
        ("cow", "is_a", "animal"),
        ("cow", "produces", "milk"),
        ("cow", "eats", "grass"),
        ("cow", "is", "large"),
        ("chicken", "is_a", "bird"),
        ("chicken", "produces", "eggs"),
        ("chicken", "eats", "grain"),
        ("chicken", "cannot", "fly_well"),
        // ═══════════════════════════════════════════════════════
        // Geography
        // ═══════════════════════════════════════════════════════
        ("paris", "capital_of", "france"),
        ("london", "capital_of", "england"),
        ("tokyo", "capital_of", "japan"),
        ("berlin", "capital_of", "germany"),
        ("rome", "capital_of", "italy"),
        ("madrid", "capital_of", "spain"),
        ("moscow", "capital_of", "russia"),
        ("beijing", "capital_of", "china"),
        ("washington", "capital_of", "united_states"),
        ("canberra", "capital_of", "australia"),
        ("ottawa", "capital_of", "canada"),
        ("cairo", "capital_of", "egypt"),
        ("new_delhi", "capital_of", "india"),
        ("bangkok", "capital_of", "thailand"),
        ("seoul", "capital_of", "south_korea"),
        ("brasilia", "capital_of", "brazil"),
        ("lima", "capital_of", "peru"),
        ("athens", "capital_of", "greece"),
        ("lisbon", "capital_of", "portugal"),
        ("vienna", "capital_of", "austria"),
        ("france", "located_in", "europe"),
        ("germany", "located_in", "europe"),
        ("japan", "located_in", "asia"),
        ("china", "located_in", "asia"),
        ("brazil", "located_in", "south_america"),
        ("egypt", "located_in", "africa"),
        ("australia", "located_in", "oceania"),
        ("canada", "located_in", "north_america"),
        ("india", "located_in", "asia"),
        ("russia", "located_in", "europe_and_asia"),
        ("nile", "is_a", "river"),
        ("nile", "located_in", "africa"),
        ("nile", "is", "longest_river_in_africa"),
        ("amazon", "is_a", "river"),
        ("amazon", "located_in", "south_america"),
        ("mount_everest", "is_a", "mountain"),
        ("mount_everest", "located_in", "asia"),
        ("mount_everest", "is", "tallest_mountain"),
        ("sahara", "is_a", "desert"),
        ("sahara", "located_in", "africa"),
        ("pacific_ocean", "is_a", "ocean"),
        ("pacific_ocean", "is", "largest_ocean"),
        ("atlantic_ocean", "is_a", "ocean"),
        ("mediterranean", "is_a", "sea"),
        ("alps", "is_a", "mountain_range"),
        ("alps", "located_in", "europe"),
        ("andes", "is_a", "mountain_range"),
        ("andes", "located_in", "south_america"),
        ("amazon_rainforest", "located_in", "south_america"),
        ("great_wall", "located_in", "china"),
        // ═══════════════════════════════════════════════════════
        // Science
        // ═══════════════════════════════════════════════════════
        ("water", "boils_at", "100_degrees_celsius"),
        ("water", "freezes_at", "0_degrees_celsius"),
        ("water", "composed_of", "hydrogen_and_oxygen"),
        ("water", "chemical_formula", "h2o"),
        ("earth", "orbits", "sun"),
        ("earth", "has", "one_moon"),
        ("earth", "is_a", "planet"),
        ("earth", "age", "4.5_billion_years"),
        ("sun", "is_a", "star"),
        ("sun", "is", "hot"),
        ("sun", "produces", "light"),
        ("sun", "produces", "heat"),
        ("moon", "orbits", "earth"),
        ("moon", "has_no", "atmosphere"),
        ("moon", "causes", "tides"),
        ("mars", "is_a", "planet"),
        ("mars", "is", "red"),
        ("mars", "has", "two_moons"),
        ("jupiter", "is_a", "planet"),
        ("jupiter", "is", "largest_planet"),
        ("saturn", "is_a", "planet"),
        ("saturn", "has", "rings"),
        ("oxygen", "is_a", "gas"),
        ("oxygen", "needed_for", "breathing"),
        ("oxygen", "needed_for", "fire"),
        ("carbon_dioxide", "is_a", "gas"),
        ("carbon_dioxide", "produced_by", "breathing"),
        ("carbon_dioxide", "absorbed_by", "plants"),
        ("nitrogen", "is_a", "gas"),
        ("nitrogen", "makes_up", "78_percent_of_atmosphere"),
        ("iron", "is_a", "metal"),
        ("iron", "is", "magnetic"),
        ("iron", "is", "strong"),
        ("gold", "is_a", "metal"),
        ("gold", "is", "valuable"),
        ("gold", "is", "yellow"),
        ("diamond", "is_a", "mineral"),
        ("diamond", "is", "hardest_natural_material"),
        ("diamond", "made_of", "carbon"),
        ("light", "travels_at", "300000_km_per_second"),
        ("light", "is", "fastest_thing"),
        ("sound", "travels_through", "air"),
        ("sound", "cannot_travel_through", "vacuum"),
        ("gravity", "pulls", "objects_down"),
        ("gravity", "keeps", "planets_in_orbit"),
        ("dna", "carries", "genetic_information"),
        ("dna", "found_in", "cells"),
        ("atom", "is", "building_block_of_matter"),
        ("atom", "has", "nucleus"),
        ("electron", "orbits", "nucleus"),
        ("electron", "has", "negative_charge"),
        ("proton", "has", "positive_charge"),
        ("neutron", "has", "no_charge"),
        // ═══════════════════════════════════════════════════════
        // Properties
        // ═══════════════════════════════════════════════════════
        ("sun", "is", "bright"),
        ("ice", "is", "cold"),
        ("ice", "is", "solid"),
        ("fire", "is", "hot"),
        ("fire", "is", "dangerous"),
        ("snow", "is", "white"),
        ("snow", "is", "cold"),
        ("sky", "is", "blue"),
        ("grass", "is", "green"),
        ("blood", "is", "red"),
        ("night", "is", "dark"),
        ("sugar", "is", "sweet"),
        ("lemon", "is", "sour"),
        ("salt", "is", "salty"),
        ("rock", "is", "hard"),
        ("cotton", "is", "soft"),
        ("feather", "is", "light"),
        ("lead", "is", "heavy"),
        ("glass", "is", "transparent"),
        ("milk", "is", "white"),
        ("coal", "is", "black"),
        ("honey", "is", "sweet"),
        ("chili", "is", "spicy"),
        ("silk", "is", "smooth"),
        ("sandpaper", "is", "rough"),
        ("rubber", "is", "flexible"),
        ("steel", "is", "strong"),
        ("paper", "is", "thin"),
        ("ocean", "is", "deep"),
        ("mountain", "is", "tall"),
        // ═══════════════════════════════════════════════════════
        // Food relations
        // ═══════════════════════════════════════════════════════
        ("rice", "is_a", "grain"),
        ("rice", "grown_in", "asia"),
        ("wheat", "is_a", "grain"),
        ("wheat", "used_for", "bread"),
        ("bread", "made_from", "flour"),
        ("flour", "made_from", "wheat"),
        ("cheese", "made_from", "milk"),
        ("butter", "made_from", "cream"),
        ("chocolate", "made_from", "cacao"),
        ("wine", "made_from", "grapes"),
        ("coffee", "made_from", "coffee_beans"),
        ("tea", "made_from", "tea_leaves"),
        ("apple", "is_a", "fruit"),
        ("apple", "color", "red"),
        ("banana", "is_a", "fruit"),
        ("banana", "color", "yellow"),
        ("orange", "is_a", "fruit"),
        ("orange", "color", "orange"),
        ("tomato", "is_a", "fruit"),
        ("tomato", "color", "red"),
        ("carrot", "is_a", "vegetable"),
        ("carrot", "color", "orange"),
        ("spinach", "is_a", "vegetable"),
        ("spinach", "color", "green"),
        ("potato", "is_a", "vegetable"),
        ("potato", "grows", "underground"),
        // ═══════════════════════════════════════════════════════
        // Technology
        // ═══════════════════════════════════════════════════════
        ("computer", "can", "process_information"),
        ("computer", "has", "processor"),
        ("computer", "has", "memory"),
        ("computer", "uses", "electricity"),
        ("internet", "connects", "computers_worldwide"),
        ("internet", "used_for", "communication"),
        ("phone", "used_for", "calling"),
        ("phone", "used_for", "messaging"),
        ("email", "is_a", "communication_method"),
        ("email", "sent_over", "internet"),
        ("robot", "is_a", "machine"),
        ("robot", "can", "perform_tasks"),
        ("satellite", "orbits", "earth"),
        ("satellite", "used_for", "communication"),
        ("battery", "stores", "energy"),
        ("solar_panel", "converts", "sunlight_to_electricity"),
        // ═══════════════════════════════════════════════════════
        // Human body
        // ═══════════════════════════════════════════════════════
        ("human", "has", "two_eyes"),
        ("human", "has", "two_hands"),
        ("human", "has", "two_legs"),
        ("human", "has", "brain"),
        ("human", "has", "heart"),
        ("heart", "pumps", "blood"),
        ("brain", "controls", "body"),
        ("lungs", "used_for", "breathing"),
        ("stomach", "digests", "food"),
        ("bones", "provide", "structure"),
        ("muscles", "enable", "movement"),
        ("skin", "protects", "body"),
        ("eyes", "used_for", "seeing"),
        ("ears", "used_for", "hearing"),
        ("nose", "used_for", "smelling"),

        // Category-level facts (enable transitive inference)
        ("animal", "has", "heart"),
        ("animal", "has", "brain"),
        ("animal", "needs", "food"),
        ("animal", "needs", "water"),
        ("animal", "can", "breathe"),
        ("animal", "can", "move"),
        ("mammal", "is_a", "animal"),
        ("mammal", "has", "warm_blood"),
        ("mammal", "has", "lungs"),
        ("mammal", "can", "breathe"),
        ("bird", "has", "feathers"),
        ("bird", "has", "beak"),
        ("bird", "lays", "eggs"),
        ("fish", "has", "gills"),
        ("fish", "lives_in", "water"),
        ("reptile", "is_a", "animal"),
        ("reptile", "has", "scales"),
        ("reptile", "is", "cold_blooded"),
        ("fruit", "grows_on", "trees"),
        ("fruit", "is", "edible"),
        ("fruit", "has", "vitamins"),
        ("vegetable", "is", "edible"),
        ("vegetable", "has", "nutrients"),
        ("country", "has", "government"),
        ("country", "has", "borders"),
        ("country", "has", "people"),
        ("planet", "orbits", "star"),
        ("planet", "has", "gravity"),
        ("star", "produces", "light"),
        ("star", "is", "very_hot"),
    ]
}

/// Returns 20+ response template pairs as (intent_pattern, template_string).
pub fn response_templates() -> Vec<(&'static str, &'static str)> {
    vec![
        ("greeting", "Hello! How can I help you today?"),
        ("greeting_morning", "Good morning! What would you like to know?"),
        ("greeting_evening", "Good evening! How can I assist you?"),
        ("farewell", "Goodbye! Have a great day!"),
        ("thanks", "You're welcome! Let me know if you need anything else."),
        ("what_is", "{subject} is {object}."),
        ("what_is_a", "{subject} is a type of {object}."),
        ("what_color", "The color of {subject} is {object}."),
        ("where_is", "{subject} is located in {object}."),
        ("where_is_capital", "{subject} is the capital of {object}."),
        ("what_does_eat", "{subject} eats {object}."),
        ("what_does_produce", "{subject} produces {object}."),
        ("what_can", "{subject} can {object}."),
        ("what_cannot", "{subject} cannot {object}."),
        ("what_has", "{subject} has {object}."),
        ("what_made_from", "{subject} is made from {object}."),
        ("what_used_for", "{subject} is used for {object}."),
        ("what_lives_in", "{subject} lives in {object}."),
        ("tell_about", "Here's what I know about {subject}: {facts}"),
        ("tell_about_short", "{subject}: {facts}"),
        ("yes_no_affirm", "Yes, {subject} is {object}."),
        ("yes_no_deny", "No, I don't have that information."),
        ("yes_no_can", "Yes, {subject} can {object}."),
        ("yes_no_cannot", "No, {subject} cannot {object}."),
        ("compare", "{subject} is {relation} than {object}."),
        ("count", "There are {object} of {subject}."),
        ("define", "{subject} is defined as {object}."),
        ("example", "An example of {subject} is {object}."),
        ("list", "Here are some {subject}: {object}."),
        ("why", "{subject} because {object}."),
        ("how", "To {subject}, you need to {object}."),
        ("when", "{subject} happens during {object}."),
        ("fact", "Did you know? {subject} {relation} {object}."),
        ("clarify", "Could you tell me more about what you'd like to know about {subject}?"),
        ("unknown", "I'm not sure about that. I know about animals, geography, science, and more. Try asking about those topics!"),
        ("error", "I didn't quite understand that. Could you rephrase your question?"),
        ("multiple_facts", "Here's what I know about {subject}: {facts}. Would you like to know more?"),
        ("confirmation", "That's correct! {subject} is indeed {object}."),
        ("suggestion", "You might also be interested in learning about {object}."),
        ("humor", "That's an interesting question! {subject} is {object}, believe it or not!"),
    ]
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_corpus_has_500_plus_sentences() {
        let corpus = large_corpus();
        assert!(
            corpus.len() >= 500,
            "Expected 500+ sentences, got {}",
            corpus.len()
        );
    }

    #[test]
    fn test_knowledge_base_has_300_plus_triples() {
        let kb = knowledge_base();
        assert!(
            kb.len() >= 300,
            "Expected 300+ triples, got {}",
            kb.len()
        );
    }

    #[test]
    fn test_response_templates_has_20_plus() {
        let templates = response_templates();
        assert!(
            templates.len() >= 20,
            "Expected 20+ templates, got {}",
            templates.len()
        );
    }

    #[test]
    fn test_corpus_no_empty_strings() {
        let corpus = large_corpus();
        for (i, sentence) in corpus.iter().enumerate() {
            assert!(!sentence.is_empty(), "Empty sentence at index {}", i);
        }
    }

    #[test]
    fn test_knowledge_base_no_empty_fields() {
        let kb = knowledge_base();
        for (i, (s, r, o)) in kb.iter().enumerate() {
            assert!(!s.is_empty(), "Empty subject at index {}", i);
            assert!(!r.is_empty(), "Empty relation at index {}", i);
            assert!(!o.is_empty(), "Empty object at index {}", i);
        }
    }
}
